DOMAIN = "comfort_climate"

CONF_ENTRY_TYPE = "entry_type"
ENTRY_TYPE_ROOM = "room"
ENTRY_TYPE_GLOBAL = "global"

# Room config (entry.data)
CONF_TEMPERATURE_SENSOR = "temperature_sensor"
CONF_HUMIDITY_SENSOR = "humidity_sensor"
CONF_COMFORT_ZONE = "comfort_zone"
CONF_HVAC_MODES = "hvac_modes"
CONF_DEFAULT_PROFILE = "default_profile"
CONF_MINIMUM_TEMPERATURE = "minimum_temperature"
CONF_MAXIMUM_TEMPERATURE = "maximum_temperature"
CONF_PRESET_ECO = "preset_eco"
CONF_PRESET_COMFORT = "preset_comfort"
CONF_PRESET_BOOST = "preset_boost"
CONF_PRESET_AWAY_LOW = "preset_away_low"
CONF_PRESET_AWAY_HIGH = "preset_away_high"
CONF_MODE_AWAY = "mode_away"
CONF_MODE_SLEEP = "mode_sleep"
CONF_MODE_HOME = "mode_home"
CONF_MODE_WARMUP = "mode_warmup"
CONF_MODE_COOLDOWN = "mode_cooldown"
CONF_MODE_ACTIVITY = "mode_activity"
CONF_MODE_BOOST = "mode_boost"
CONF_MODE_AWAY_PROFILE = "mode_away_profile"
CONF_MODE_SLEEP_PROFILE = "mode_sleep_profile"
CONF_MODE_HOME_PROFILE = "mode_home_profile"
CONF_MODE_WARMUP_PROFILE = "mode_warmup_profile"
CONF_MODE_COOLDOWN_PROFILE = "mode_cooldown_profile"
CONF_MODE_ACTIVITY_PROFILE = "mode_activity_profile"
CONF_MODE_BOOST_PROFILE = "mode_boost_profile"
CONF_MODE_AWAY_ENABLED = "mode_away_enabled"
CONF_MODE_SLEEP_ENABLED = "mode_sleep_enabled"
CONF_MODE_WARMUP_ENABLED = "mode_warmup_enabled"
CONF_MODE_COOLDOWN_ENABLED = "mode_cooldown_enabled"
CONF_MODE_ACTIVITY_ENABLED = "mode_activity_enabled"
CONF_MODE_BOOST_ENABLED = "mode_boost_enabled"
CONF_HOUSE_MODE_ENTITY = "house_mode_entity"

# Options (entry.options)
CONF_DEVICES = "devices"

# Per-device config
CONF_DEVICE_ENTITY = "entity_id"
CONF_DEVICE_LABEL = "label"
CONF_DEVICE_ROLE = "role"
CONF_DEVICE_ACTIVATION_POINT = "activation_point"
CONF_DEVICE_ACTIVATE_OFFSET = "activate_offset"
CONF_DEVICE_DEACTIVATE_OFFSET = "deactivate_offset"
CONF_DEVICE_HVAC_MODE_ON = "hvac_mode_on"
CONF_DEVICE_EMERGENCY_ENABLED = "emergency_enabled"
# Optional: offset from room setpoint applied to device target when activating.
# Negative for cooling (e.g. -3 → set AC to setpoint-3°C so it actually works),
# positive for heating (e.g. +3 → set thermostat to setpoint+3°C).
CONF_DEVICE_TARGET_TEMP_OFFSET = "target_temp_offset"
# Dehumidifier-specific
CONF_DEVICE_HUMIDITY_THRESHOLD = "humidity_threshold"
CONF_DEVICE_HUMIDITY_HYSTERESIS = "humidity_hysteresis"
CONF_DEVICE_DEHUMIDIFY_ONLY_WHEN_IDLE = "dehumidify_only_when_idle"

ROLE_HEATING = "heating"
ROLE_COOLING = "cooling"
ROLE_DEHUMIDIFY = "dehumidify"

MODE_AWAY = "away"
MODE_SLEEP = "sleep"
MODE_HOME = "home"
# Use Home Assistant's standard climate preset names so the frontend can show
# built-in preset icons instead of the generic fallback bullet.
MODE_WARMUP = "comfort"
MODE_COOLDOWN = "eco"
MODE_ACTIVITY = "activity"
MODE_BOOST = "boost"
MODE_OPTIONS = [MODE_AWAY, MODE_SLEEP, MODE_HOME, MODE_WARMUP, MODE_COOLDOWN, MODE_ACTIVITY, MODE_BOOST]
OPTIONAL_MODE_OPTIONS = [MODE_AWAY, MODE_SLEEP, MODE_WARMUP, MODE_COOLDOWN, MODE_ACTIVITY, MODE_BOOST]

PROFILE_RELAXED = "relaxed"
PROFILE_BALANCED = "balanced"
PROFILE_RESPONSIVE = "responsive"
PROFILE_AGGRESSIVE = "aggressive"
PROFILE_OPTIONS = [PROFILE_RELAXED, PROFILE_BALANCED, PROFILE_RESPONSIVE, PROFILE_AGGRESSIVE]

CONF_PROFILE_RELAXED_COMFORT_MULTIPLIER = "profile_relaxed_comfort_multiplier"
CONF_PROFILE_RELAXED_POINT_SPACING = "profile_relaxed_point_spacing"
CONF_PROFILE_BALANCED_COMFORT_MULTIPLIER = "profile_balanced_comfort_multiplier"
CONF_PROFILE_BALANCED_POINT_SPACING = "profile_balanced_point_spacing"
CONF_PROFILE_RESPONSIVE_COMFORT_MULTIPLIER = "profile_responsive_comfort_multiplier"
CONF_PROFILE_RESPONSIVE_POINT_SPACING = "profile_responsive_point_spacing"
CONF_PROFILE_AGGRESSIVE_COMFORT_MULTIPLIER = "profile_aggressive_comfort_multiplier"
CONF_PROFILE_AGGRESSIVE_POINT_SPACING = "profile_aggressive_point_spacing"

DEFAULT_COMFORT_ZONE = 1.0
DEFAULT_PROFILE = PROFILE_BALANCED
DEFAULT_PRESET_ECO = 17.0
DEFAULT_PRESET_COMFORT = 21.0
DEFAULT_PRESET_BOOST = 23.0
DEFAULT_PRESET_AWAY_LOW = 15.0
DEFAULT_PRESET_AWAY_HIGH = 30.0
DEFAULT_MODE_AWAY = 16.0
DEFAULT_MODE_SLEEP = 18.0
DEFAULT_MODE_HOME = 21.0
DEFAULT_MODE_WARMUP = 22.0
DEFAULT_MODE_COOLDOWN = 19.0
DEFAULT_MODE_ACTIVITY = 19.5
DEFAULT_MODE_BOOST = 23.0
DEFAULT_MODE_PROFILE_AWAY = PROFILE_RELAXED
DEFAULT_MODE_PROFILE_SLEEP = PROFILE_RELAXED
DEFAULT_MODE_PROFILE_HOME = PROFILE_BALANCED
DEFAULT_MODE_PROFILE_WARMUP = PROFILE_AGGRESSIVE
DEFAULT_MODE_PROFILE_COOLDOWN = PROFILE_AGGRESSIVE
DEFAULT_MODE_PROFILE_ACTIVITY = PROFILE_RESPONSIVE
DEFAULT_MODE_PROFILE_BOOST = PROFILE_AGGRESSIVE
DEFAULT_MODE_AWAY_ENABLED = True
DEFAULT_MODE_SLEEP_ENABLED = True
DEFAULT_MODE_WARMUP_ENABLED = True
DEFAULT_MODE_COOLDOWN_ENABLED = True
DEFAULT_MODE_ACTIVITY_ENABLED = False
DEFAULT_MODE_BOOST_ENABLED = False
DEFAULT_PROFILE_RELAXED_COMFORT_MULTIPLIER = 1.5
DEFAULT_PROFILE_RELAXED_POINT_SPACING = 0.8
DEFAULT_PROFILE_BALANCED_COMFORT_MULTIPLIER = 1.0
DEFAULT_PROFILE_BALANCED_POINT_SPACING = 0.5
DEFAULT_PROFILE_RESPONSIVE_COMFORT_MULTIPLIER = 0.7
DEFAULT_PROFILE_RESPONSIVE_POINT_SPACING = 0.4
DEFAULT_PROFILE_AGGRESSIVE_COMFORT_MULTIPLIER = 0.4
DEFAULT_PROFILE_AGGRESSIVE_POINT_SPACING = 0.2
DEFAULT_MIN_TEMP = 5.0
DEFAULT_MAX_TEMP = 35.0
DEFAULT_TEMP_STEP = 0.1
DEFAULT_ACTIVATE_OFFSET = 0.0
DEFAULT_MANUAL_HOLD_HOURS = 2.0
CONF_MANUAL_HOLD_HOURS = "manual_hold_hours"
DEFAULT_MANUAL_HOLD_CONFIRM_SECONDS = 30.0
CONF_MANUAL_HOLD_CONFIRM_SECONDS = "manual_hold_confirm_seconds"
DEFAULT_DEACTIVATE_OFFSET = 0.5
DEFAULT_HUMIDITY_THRESHOLD = 65.0
DEFAULT_HUMIDITY_HYSTERESIS = 5.0

# When True the room inherits preset temperatures from the Global Defaults entry
# instead of its own local values.
CONF_USE_GLOBAL_PRESETS = "use_global_presets"
CONF_FLOOR_NAMES = "floor_names"

MODE_ENABLE_KEYS = {
    MODE_AWAY: CONF_MODE_AWAY_ENABLED,
    MODE_SLEEP: CONF_MODE_SLEEP_ENABLED,
    MODE_WARMUP: CONF_MODE_WARMUP_ENABLED,
    MODE_COOLDOWN: CONF_MODE_COOLDOWN_ENABLED,
    MODE_ACTIVITY: CONF_MODE_ACTIVITY_ENABLED,
    MODE_BOOST: CONF_MODE_BOOST_ENABLED,
}

MODE_ENABLE_DEFAULTS = {
    CONF_MODE_AWAY_ENABLED: DEFAULT_MODE_AWAY_ENABLED,
    CONF_MODE_SLEEP_ENABLED: DEFAULT_MODE_SLEEP_ENABLED,
    CONF_MODE_WARMUP_ENABLED: DEFAULT_MODE_WARMUP_ENABLED,
    CONF_MODE_COOLDOWN_ENABLED: DEFAULT_MODE_COOLDOWN_ENABLED,
    CONF_MODE_ACTIVITY_ENABLED: DEFAULT_MODE_ACTIVITY_ENABLED,
    CONF_MODE_BOOST_ENABLED: DEFAULT_MODE_BOOST_ENABLED,
}

ATTR_COMFORT_ZONE = "comfort_zone"
ATTR_LOWER_THRESHOLD = "lower_threshold"
ATTR_UPPER_THRESHOLD = "upper_threshold"
ATTR_EFFECTIVE_SETPOINT = "effective_setpoint"
ATTR_ACTIVE_DEVICES = "active_devices"
ATTR_CURRENT_HUMIDITY = "current_humidity"
